work-in-progress: gradual evolution in invocation style

diff --git a/restore_example/DEMO b/restore_example/DEMO
--- a/restore_example/DEMO
+++ b/restore_example/DEMO
@@ -3,7 +3,7 @@
 # step 1: `cp globals.example globals.custom` # or choose another name
 # step 2: Edit globals.custom as appropriate for your installation
 # step 3: `bash -c ". setup_env globals.custom`, which generates
-#           ./env-for-TLDR,
+#           ./env-for-DEMO,
 #           ./tardis/s3/dest.config,
 #           ./env-for-compose-to-source.sh, and
 #           ./tags-for-compose-to-source.sh
@@ -11,21 +11,21 @@
 #           ./tardis/s3/dest.s3cfg
 #         TODO Explain how to do this using the copy of 's3cmd' in the TARDIS
 # step 5: Run as appropriate one or more of the following
-#           `bash TLDR fresh`
-#           `bash TLDR restore`
-#           `bash TLDR run`
+#           `bash DEMO fresh`
+#           `bash DEMO restore`
+#           `bash DEMO run`
 
-# set TLDR_RUN_MODE to second argument if provided: 'fresh', 'run', or 'restore'
+# set DEMO_RUN_MODE to second argument if provided: 'fresh', 'run', or 'restore'
 if [ ! -z "$1" ]; then
-  TLDR_RUN_MODE="$1"
+  DEMO_RUN_MODE="$1"
 fi
 
 # get required environment variables (e.g., generated by '. setup_env globals.custom')
-. env-for-TLDR
+. env-for-DEMO
 
 # show the required envars that we have; abort if some are not set
 echo "
-TLDR_RUN_MODE       : ${TLDR_RUN_MODE:?}
+DEMO_RUN_MODE       : ${DEMO_RUN_MODE:?}
 MY_INSTANCE         : ${MY_INSTANCE:?}
 MY_BUCKET_PREFIX    : ${MY_BUCKET_PREFIX:?}
 MY_GALAXY_POSTGRES  : ${MY_GALAXY_POSTGRES:?}
@@ -39,7 +39,7 @@ MY_GALAXY_TOOL_DEPS_CONDA_BASE_PYTHON_VERSION : ${MY_GALAXY_TOOL_DEPS_CONDA_BASE
 ls -l tardis/s3/dest.s3cfg tardis/s3/dest.config
 "
 
-# Right now, TLDR assumes that we are running with usernetes' rootless dockerd
+# Right now, DEMO assumes that we are running with usernetes' rootless dockerd
 #   In the future, it may be desirable to override as ROODO=sudo to use sudo with the rooted dockerd.
 ROODO=${ROODO:-'rootlesskit --disable-host-loopback'}
 
@@ -73,11 +73,11 @@ swab_orphans() {
 #     comment out the next line after the first pull:
 docker-compose -f ${MY_COMPOSE_FILE:?} pull
 
-case ${TLDR_RUN_MODE:?} in
+case ${DEMO_RUN_MODE:?} in
   run)
     echo "#*#*#*#*#*#*#*#  Running Galaxy with neither initialization nor restoration  #*#*#*#*#*#*#*#"
     if [ ! -f ${MY_GALAXY_EXPORT:?}/config/tool_conf.xml ]; then
-      echo "Please run TLDR with TLDR_RUN_MODE=fresh"
+      echo "Please run DEMO with DEMO_RUN_MODE=fresh"
       exit 1
     fi
     ;;
@@ -95,19 +95,19 @@ case ${TLDR_RUN_MODE:?} in
     echo "#*#*#*#*#*#*#*#  Fetching and applying Galaxy configuration from S3  #*#*#*#*#*#*#*#"
     # You may want to use --Miniconda2 when Galaxy uses python2, but that may not even be necessary
     # You probably ought to use --Miniconda3 when Galaxy uses python3
-    ./compose_restore.sh --Miniconda${MY_GALAXY_TOOL_DEPS_CONDA_BASE_PYTHON_VERSION}; if [ $? -ne 0 ]; then echo "FATAL: Updating conda failed - aborting TLDR"; exit 1; fi
+    ./compose_restore.sh --Miniconda${MY_GALAXY_TOOL_DEPS_CONDA_BASE_PYTHON_VERSION}; if [ $? -ne 0 ]; then echo "FATAL: Updating conda failed - aborting DEMO"; exit 1; fi
     # Restore Galaxy configuration
-    ./compose_restore.sh --retrieve_config --apply_config; if [ $? -ne 0 ]; then echo "FATAL: Retrieving or applying config failed - aborting TLDR"; exit 1; fi
+    ./compose_restore.sh --retrieve_config --apply_config; if [ $? -ne 0 ]; then echo "FATAL: Retrieving or applying config failed - aborting DEMO"; exit 1; fi
     # Fetch datasets from S3 backup; you won't want to do this if you are using an S3 bucket as your object store
-    ./compose_restore.sh --datasets; if [ $? -ne 0 ]; then echo "FATAL: Restoring datasets failed - aborting TLDR"; exit 1; fi
+    ./compose_restore.sh --datasets; if [ $? -ne 0 ]; then echo "FATAL: Restoring datasets failed - aborting DEMO"; exit 1; fi
     # Replace database schema and contents from S3 backup; once you start using Galaxy, datasets not tracked in database WILL be overwritten!
-    ./compose_restore.sh --database; if [ $? -ne 0 ]; then echo "FATAL: Restoring database failed - aborting TLDR"; exit 1; fi
+    ./compose_restore.sh --database; if [ $? -ne 0 ]; then echo "FATAL: Restoring database failed - aborting DEMO"; exit 1; fi
     echo "#*#*#*#*#*#*#*#  Upgrading Galaxy PostgreSQL database  #*#*#*#*#*#*#*#"
     # Upgrade the database to match the inited Galaxy's version
     ./compose_start.sh --init-only --upgrade-db
     ;;
   *)
-    echo "Unknown value ${TLDR_RUN_MODE:?} for TLDR_RUN_MODE"
+    echo "Unknown value ${DEMO_RUN_MODE:?} for DEMO_RUN_MODE"
     echo "Please choose one of 'restore', 'fresh', or 'run'"
     echo exit 1
     ;;
